name: tnt_scanner
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: #Localization for Android
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1 #Localization for iOS
  audioplayers: ^0.14.0 #Play sound
  auto_route: ^0.2.2 #Page navigation
  badges: ^1.1.0 #Badge for bottom navigation
  csv: ^4.0.3 #Csv file exporter
  double_back_to_close_app: ^0.1.2 #Double back close the app
  equatable: ^1.0.3 #Compare objects
  flushbar: ^1.9.1 #Custom snackbar
  flutter_progress_button: ^1.0.0 #Progress button loading
  flutter_launcher_icons: ^0.7.4 #Flutter launcher icon
  font_awesome_flutter: ^8.5.0 #Custom flutter icon
  intl: ^0.16.0 #Internationalization and localization date time format
  keyboard_visibility: ^0.5.6 #Keyboard display listener
  states_rebuilder: ^1.14.2 #State rebuilder state management
  spreadsheet_decoder: ^1.1.0 #Excel file decoder
  permission_handler: ^4.2.0+hotfix.2 #Storage permission

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  auto_route_generator: ^0.2.1+3
  flutter_native_splash: ^0.1.5 #native flutter splash screen

flutter_native_splash:
  image: assets/dcs.png
  color: "FFFFFF"
  fill: false
  android_disable_fullscreen: true
#flutter pub pub run flutter_native_splash:create

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/i18n/en.json
   - assets/i18n/ar.json
   - assets/dcs_about.png
   - assets/error.wav
   - assets/success.wav

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
